// banderas.js

// Array of flag objects with their URLs and names
const flags = [
    { url: './flags/ad.webp', name: 'Andorra' },
    { url: './flags/ae.webp', name: 'Emiratos Árabes Unidos' },
    { url: './flags/af.webp', name: 'Afganistán' },
    { url: './flags/ag.webp', name: 'Antigua y Barbuda' },
    { url: './flags/ai.webp', name: 'Anguila' },
    { url: './flags/al.webp', name: 'Albania' },
    { url: './flags/am.webp', name: 'Armenia' },
    { url: './flags/ao.webp', name: 'Angola' },
    { url: './flags/aq.webp', name: 'Antártida' },
    { url: './flags/ar.webp', name: 'Argentina' },
    { url: './flags/as.webp', name: 'Samoa Americana' },
    { url: './flags/at.webp', name: 'Austria' },
    { url: './flags/au.webp', name: 'Australia' },
    { url: './flags/aw.webp', name: 'Aruba' },
    { url: './flags/ax.webp', name: 'Åland' },
    { url: './flags/az.webp', name: 'Azerbaiyán' },
    { url: './flags/ba.webp', name: 'Bosnia y Herzegovina' },
    { url: './flags/bb.webp', name: 'Barbados' },
    { url: './flags/bd.webp', name: 'Bangladés' },
    { url: './flags/be.webp', name: 'Bélgica' },
    { url: './flags/bf.webp', name: 'Burkina Faso' },
    { url: './flags/bg.webp', name: 'Bulgaria' },
    { url: './flags/bh.webp', name: 'Baréin' },
    { url: './flags/bi.webp', name: 'Burundi' },
    { url: './flags/bj.webp', name: 'Benín' },
    { url: './flags/bl.webp', name: 'San Bartolomé' },
    { url: './flags/bm.webp', name: 'Bermudas' },
    { url: './flags/bn.webp', name: 'Brunéi' },
    { url: './flags/bo.webp', name: 'Bolivia' },
    { url: './flags/bq.webp', name: 'Bonaire, San Eustaquio y Saba' },
    { url: './flags/br.webp', name: 'Brasil' },
    { url: './flags/bs.webp', name: 'Bahamas' },
    { url: './flags/bt.webp', name: 'Bután' },
    { url: './flags/bv.webp', name: 'Bouvet' },
    { url: './flags/bw.webp', name: 'Botsuana' },
    { url: './flags/by.webp', name: 'Bielorrusia' },
    { url: './flags/bz.webp', name: 'Belice' },
    { url: './flags/ca.webp', name: 'Canadá' },
    { url: './flags/cc.webp', name: 'Islas Cocos' },
    { url: './flags/cd.webp', name: 'República Democrática del Congo' },
    { url: './flags/cf.webp', name: 'República Centroafricana' },
    { url: './flags/cg.webp', name: 'República del Congo' },
    { url: './flags/ch.webp', name: 'Suiza' },
    { url: './flags/ci.webp', name: 'Costa de Marfil' },
    { url: './flags/ck.webp', name: 'Islas Cook' },
    { url: './flags/cl.webp', name: 'Chile' },
    { url: './flags/cm.webp', name: 'Camerún' },
    { url: './flags/cn.webp', name: 'China' },
    { url: './flags/co.webp', name: 'Colombia' },
    { url: './flags/cr.webp', name: 'Costa Rica' },
    { url: './flags/cu.webp', name: 'Cuba' },
    { url: './flags/cv.webp', name: 'Cabo Verde' },
    { url: './flags/cw.webp', name: 'Curazao' },
    { url: './flags/cx.webp', name: 'Islas Christmas' },
    { url: './flags/cy.webp', name: 'Chipre' },
    { url: './flags/cz.webp', name: 'República Checa' },
    { url: './flags/de.webp', name: 'Alemania' },
    { url: './flags/dj.webp', name: 'Yibuti' },
    { url: './flags/dk.webp', name: 'Dinamarca' },
    { url: './flags/dm.webp', name: 'Dominica' },
    { url: './flags/do.webp', name: 'República Dominicana' },
    { url: './flags/dz.webp', name: 'Argelia' },
    { url: './flags/ec.webp', name: 'Ecuador' },
    { url: './flags/ee.webp', name: 'Estonia' },
    { url: './flags/eg.webp', name: 'Egipto' },
    { url: './flags/eh.webp', name: 'Sáhara Occidental' },
    { url: './flags/er.webp', name: 'Eritrea' },
    { url: './flags/es.webp', name: 'España' },
    { url: './flags/et.webp', name: 'Etiopía' },
    { url: './flags/fi.webp', name: 'Finlandia' },
    { url: './flags/fj.webp', name: 'Fiyi' },
    { url: './flags/fk.webp', name: 'Malvinas' },
    { url: './flags/fm.webp', name: 'Micronesia' },
    { url: './flags/fo.webp', name: 'Islas Feroe' },
    { url: './flags/fr.webp', name: 'Francia' },
    { url: './flags/ga.webp', name: 'Gabón' },
    { url: './flags/gb-eng.webp', name: 'Inglaterra' },
    { url: './flags/gb-nir.webp', name: 'Irlanda del Norte' },
    { url: './flags/gb-sct.webp', name: 'Escocia' },
    { url: './flags/gb-wls.webp', name: 'Gales' },
    { url: './flags/gb.webp', name: 'Reino Unido' },
    { url: './flags/gd.webp', name: 'Granada' },
    { url: './flags/ge.webp', name: 'Georgia' },
    { url: './flags/gf.webp', name: 'Guayana Francesa' },
    { url: './flags/gg.webp', name: 'Guernsey' },
    { url: './flags/gh.webp', name: 'Ghana' },
    { url: './flags/gi.webp', name: 'Gibraltar' },
    { url: './flags/gl.webp', name: 'Groenlandia' },
    { url: './flags/gm.webp', name: 'Gambia' },
    { url: './flags/gn.webp', name: 'Guinea' },
    { url: './flags/gp.webp', name: 'Guadalupe' },
    { url: './flags/gq.webp', name: 'Guinea Ecuatorial' },
    { url: './flags/gr.webp', name: 'Grecia' },
    { url: './flags/gs.webp', name: 'Georgia del Sur y Sandwich del Sur' },
    { url: './flags/gt.webp', name: 'Guatemala' },
    { url: './flags/gu.webp', name: 'Guam' },
    { url: './flags/gw.webp', name: 'Guinea-Bisáu' },
    { url: './flags/gy.webp', name: 'Guyana' },
    { url: './flags/hk.webp', name: 'Hong Kong' },
    { url: './flags/hm.webp', name: 'Islas Heard y McDonald' },
    { url: './flags/hn.webp', name: 'Honduras' },
    { url: './flags/hr.webp', name: 'Croacia' },
    { url: './flags/ht.webp', name: 'Haití' },
    { url: './flags/hu.webp', name: 'Hungría' },
    { url: './flags/id.webp', name: 'Indonesia' },
    { url: './flags/ie.webp', name: 'Irlanda' },
    { url: './flags/il.webp', name: 'Israel' },
    { url: './flags/im.webp', name: 'Isla de Man' },
    { url: './flags/in.webp', name: 'India' },
    { url: './flags/io.webp', name: 'Territorio Británico del Océano Índico' },
    { url: './flags/iq.webp', name: 'Irak' },
    { url: './flags/ir.webp', name: 'Irán' },
    { url: './flags/is.webp', name: 'Islandia' },
    { url: './flags/it.webp', name: 'Italia' },
    { url: './flags/je.webp', name: 'Jersey' },
    { url: './flags/jm.webp', name: 'Jamaica' },
    { url: './flags/jo.webp', name: 'Jordania' },
    { url: './flags/jp.webp', name: 'Japón' },
    { url: './flags/ke.webp', name: 'Kenia' },
    { url: './flags/kg.webp', name: 'Kirguistán' },
    { url: './flags/kh.webp', name: 'Camboya' },
    { url: './flags/ki.webp', name: 'Kiribati' },
    { url: './flags/km.webp', name: 'Comoras' },
    { url: './flags/kn.webp', name: 'San Cristóbal y Nieves' },
    { url: './flags/kp.webp', name: 'Corea del Norte' },
    { url: './flags/kr.webp', name: 'Corea del Sur' },
    { url: './flags/kw.webp', name: 'Kuwait' },
    { url: './flags/ky.webp', name: 'Islas Caimán' },
    { url: './flags/kz.webp', name: 'Kazajistán' },
    { url: './flags/la.webp', name: 'Laos' },
    { url: './flags/lb.webp', name: 'Líbano' },
    { url: './flags/lc.webp', name: 'Santa Lucía' },
    { url: './flags/li.webp', name: 'Liechtenstein' },
    { url: './flags/lk.webp', name: 'Sri Lanka' },
    { url: './flags/lr.webp', name: 'Liberia' },
    { url: './flags/ls.webp', name: 'Lesoto' },
    { url: './flags/lt.webp', name: 'Lituania' },
    { url: './flags/lu.webp', name: 'Luxemburgo' },
    { url: './flags/lv.webp', name: 'Letonia' },
    { url: './flags/ly.webp', name: 'Libia' },
    { url: './flags/ma.webp', name: 'Marruecos' },
    { url: './flags/mc.webp', name: 'Mónaco' },
    { url: './flags/md.webp', name: 'Moldavia' },
    { url: './flags/me.webp', name: 'Montenegro' },
    { url: './flags/mf.webp', name: 'San Martín' },
    { url: './flags/mg.webp', name: 'Madagascar' },
    { url: './flags/mh.webp', name: 'Islas Marshall' },
    { url: './flags/mk.webp', name: 'Macedonia del Norte' },
    { url: './flags/ml.webp', name: 'Malí' },
    { url: './flags/mm.webp', name: 'Birmania' },
    { url: './flags/mn.webp', name: 'Mongolia' },
    { url: './flags/mo.webp', name: 'Macao' },
    { url: './flags/mp.webp', name: 'Islas Marianas del Norte' },
    { url: './flags/mq.webp', name: 'Martinica' },
    { url: './flags/mr.webp', name: 'Mauritania' },
    { url: './flags/ms.webp', name: 'Montserrat' },
    { url: './flags/mt.webp', name: 'Malta' },
    { url: './flags/mu.webp', name: 'Mauricio' },
    { url: './flags/mv.webp', name: 'Maldivas' },
    { url: './flags/mw.webp', name: 'Malawi' },
    { url: './flags/mx.webp', name: 'México' },
    { url: './flags/my.webp', name: 'Malasia' },
    { url: './flags/mz.webp', name: 'Mozambique' },
    { url: './flags/na.webp', name: 'Namibia' },
    { url: './flags/nc.webp', name: 'Nueva Caledonia' },
    { url: './flags/ne.webp', name: 'Níger' },
    { url: './flags/nf.webp', name: 'Isla Norfolk' },
    { url: './flags/ng.webp', name: 'Nigeria' },
    { url: './flags/ni.webp', name: 'Nicaragua' },
    { url: './flags/nl.webp', name: 'Países Bajos' },
    { url: './flags/no.webp', name: 'Noruega' },
    { url: './flags/np.webp', name: 'Nepal' },
    { url: './flags/nr.webp', name: 'Nauru' },
    { url: './flags/nu.webp', name: 'Niue' },
    { url: './flags/nz.webp', name: 'Nueva Zelanda' },
    { url: './flags/om.webp', name: 'Omán' },
    { url: './flags/pa.webp', name: 'Panamá' },
    { url: './flags/pe.webp', name: 'Perú' },
    { url: './flags/pf.webp', name: 'Polinesia Francesa' },
    { url: './flags/pg.webp', name: 'Papúa Nueva Guinea' },
    { url: './flags/ph.webp', name: 'Filipinas' },
    { url: './flags/pk.webp', name: 'Pakistán' },
    { url: './flags/pl.webp', name: 'Polonia' },
    { url: './flags/pm.webp', name: 'San Pedro y Miquelón' },
    { url: './flags/pn.webp', name: 'Islas Pitcairn' },
    { url: './flags/pr.webp', name: 'Puerto Rico' },
    { url: './flags/ps.webp', name: 'Palestina' },
    { url: './flags/pt.webp', name: 'Portugal' },
    { url: './flags/pw.webp', name: 'Palaú' },
    { url: './flags/py.webp', name: 'Paraguay' },
    { url: './flags/qa.webp', name: 'Catar' },
    { url: './flags/re.webp', name: 'Reunión' },
    { url: './flags/ro.webp', name: 'Rumania' },
    { url: './flags/rs.webp', name: 'Serbia' },
    { url: './flags/ru.webp', name: 'Rusia' },
    { url: './flags/rw.webp', name: 'Ruanda' },
    { url: './flags/sa.webp', name: 'Arabia Saudita' },
    { url: './flags/sb.webp', name: 'Islas Salomón' },
    { url: './flags/sc.webp', name: 'Seychelles' },
    { url: './flags/sd.webp', name: 'Sudán' },
    { url: './flags/se.webp', name: 'Suecia' },
    { url: './flags/sg.webp', name: 'Singapur' },
    { url: './flags/sh.webp', name: 'Santa Helena' },
    { url: './flags/si.webp', name: 'Eslovenia' },
    { url: './flags/sj.webp', name: 'Svalbard y Jan Mayen' },
    { url: './flags/sk.webp', name: 'Eslovaquia' },
    { url: './flags/sl.webp', name: 'Sierra Leona' },
    { url: './flags/sm.webp', name: 'San Marino' },
    { url: './flags/sn.webp', name: 'Senegal' },
    { url: './flags/so.webp', name: 'Somalia' },
    { url: './flags/sr.webp', name: 'Surinam' },
    { url: './flags/ss.webp', name: 'Sudán del Sur' },
    { url: './flags/st.webp', name: 'Santo Tomé y Príncipe' },
    { url: './flags/sv.webp', name: 'El Salvador' },
    { url: './flags/sx.webp', name: 'Sint Maarten' },
    { url: './flags/sy.webp', name: 'Siria' },
    { url: './flags/sz.webp', name: 'Suazilandia' },
    { url: './flags/tc.webp', name: 'Islas Turcas y Caicos' },
    { url: './flags/td.webp', name: 'Chad' },
    { url: './flags/tf.webp', name: 'Territorios Australes Franceses' },
    { url: './flags/tg.webp', name: 'Togo' },
    { url: './flags/th.webp', name: 'Tailandia' },
    { url: './flags/tj.webp', name: 'Tayikistán' },
    { url: './flags/tk.webp', name: 'Tokelau' },
    { url: './flags/tl.webp', name: 'Timor Oriental' },
    { url: './flags/tm.webp', name: 'Turkmenistán' },
    { url: './flags/tn.webp', name: 'Túnez' },
    { url: './flags/to.webp', name: 'Tonga' },
    { url: './flags/tr.webp', name: 'Turquía' },
    { url: './flags/tt.webp', name: 'Trinidad y Tobago' },
    { url: './flags/tv.webp', name: 'Tuvalu' },
    { url: './flags/tw.webp', name: 'Taiwán' },
    { url: './flags/tz.webp', name: 'Tanzania' },
    { url: './flags/ua.webp', name: 'Ucrania' },
    { url: './flags/ug.webp', name: 'Uganda' },
    { url: './flags/um.webp', name: 'Islas Ultramarinas de EE. UU.' },
    { url: './flags/us.webp', name: 'Estados Unidos' },
    { url: './flags/uy.webp', name: 'Uruguay' },
    { url: './flags/uz.webp', name: 'Uzbekistán' },
    { url: './flags/va.webp', name: 'Vaticano' },
    { url: './flags/vc.webp', name: 'San Vicente y las Granadinas' },
    { url: './flags/ve.webp', name: 'Venezuela' },
    { url: './flags/vg.webp', name: 'Islas Vírgenes Británicas' },
    { url: './flags/vi.webp', name: 'Islas Vírgenes de EE. UU.' },
    { url: './flags/vn.webp', name: 'Vietnam' },
    { url: './flags/vu.webp', name: 'Vanuatu' },
    { url: './flags/wf.webp', name: 'Wallis y Futuna' },
    { url: './flags/ws.webp', name: 'Samoa' },
    { url: './flags/xk.webp', name: 'Kosovo' },
    { url: './flags/ye.webp', name: 'Yemen' },
    { url: './flags/yt.webp', name: 'Mayotte' },
    { url: './flags/za.webp', name: 'Sudáfrica' },
    { url: './flags/zm.webp', name: 'Zambia' },
    { url: './flags/zw.webp', name: 'Zimbabue' }
];

// Export the flags array for use in other scripts
export { flags };
